application: techno-is-the-word
version: 3-live
runtime: python27
api_version: 1
threadsafe: false

default_expiration: 1d

libraries:
- name: numpy
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: setuptools
  version: latest


# ----------------------------------------
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.orig$
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^db/.*

# ----------------------------------------

builtins:
- admin_redirect: on
- datastore_admin: on
- deferred: on

inbound_services:
- warmup

admin_console:
  pages:
  - name: Sample List
    url: /_ah/nimda/samples
  - name: Upload Sample
    url: /_ah/nimda/upload
  - name: Word List
    url: /_ah/nimda/list
  - name: Flush Words
    url: /_ah/nimda/flush
  - name: App Stats
    url: /_ah/stats/


# ----------------------------------------
error_handlers:
  - file: app-error.html

  - error_code: over_quota
    file: app-over-quota.html

# ----------------------------------------

handlers:
# Static data.
- url: /css
  static_dir: static/css
- url: /img
  static_dir: static/img
- url: /js
  static_dir: static/js

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /apple-touch-icon.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png
- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# Admin pages.
- url: /_ah/nimda/.*
  script: admin.application
  login: admin

- url: /_ah/remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/warmup
  script: admin.application
  login: admin

- url: /_ah/stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /_ah/bulkupdate/admin/.*
  script: bulkupdate/handler.py
  login: admin

- url: /_ah/ereporter.*
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin

# Main site.
- url: /.*
  script: main.application
